### ISSUE TITLE
webpack hot loading

### ISSUE THREAD

**Issue by thiagoc7** [rofrischmann/react-look#103]
Hi, thanks for this amazing addon!

Can you use `react-look` with hot loading?
For me it's not working. Everything else is updated on the browser.
When I change a style, I even get a new webpack building on the terminal, but the code is not updated in the browser.

I'm using a very simple webpack config, [here](https://github.com/thereactivestack/meteor-webpack-react-kickstart/blob/master/webpack/development.config.js).

Thanks!

**Comment by rofrischmann** [comment]
Hey @thiagoc7,

Actually I have never used webpack by now. I have been using Browserify with the livereactload package and had no problems with this.

I will investigate a bit further during this week and hopefully I can help you out!

**Comment by thiagoc7** [comment]
Thanks @rofrischmann!
Please let me know if I can help.

**Comment by rofrischmann** [comment]
@thiagoc7 would save a lot of time to have a working project to test with as I am totally not familiar with webpack :p if you could provide a simple example with look not working as expected, it would be awesome!

**Comment by thiagoc7** [comment]
Hi @rofrischmann,
I was using a react + meteor +webpack boilerplate, but I think that won't help much, it's very opinated.

I tried to reproduce the error with [react-transform-boilerplate](https://github.com/gaearon/react-transform-boilerplate), as it's the simplest one I could find, but now I have another issue:

`Uncaught Error: Invariant Violation: LookTest.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.`

I created a [repo](https://github.com/thiagoc7/react-look-webpack) with this config, and with raidum installed, so you can see that it works. If you just comment out `@Look` it works.

thanks!

**Comment by dnusca** [comment]
@thiagoc7 I believe your latest issue (Invariant Violation) may be due to two different versions of React.js being loaded.

Please see the first tip here for more information on how to resolve this: https://medium.com/@dan_abramov/two-weird-tricks-that-fix-react-7cf9bbdef375

**Comment by rofrischmann** [comment]
Thanks @dnusca for the hint. If this fix the problem, please try to do so @thiagoc7. If not: let me know and I will investigate some time next week.

**Comment by thiagoc7** [comment]
Thanks @dnusca, that's the problem.
Using `react 0.14` solved both issues.
@rofrischmann thanks again for this addon!
