### ISSUE TITLE
Parsing pseudo-classes and stateful styles from imported style object

### ISSUE THREAD

**Issue by dnusca** [rofrischmann/react-look#104]
Hi there,

First of all great styling library, really enjoying it.

I'm having a problem where if I pass an imported object to styles then Look is not parsing the pseudo-classes or stateful styles keys.

For example:

in listStyles.js 

```javascript
export const list = {
    button: {
		width: '25%'
        ':hover': {
            color: '#ffffff'
        }
    }
}
```

and in my component

```javascript
import React from 'react';
import Look from 'react-look/dom';
import {list as listStyle} from '../../styles/listStyles';

@Look
class ItemListNode extends React.Component {

	styles = {
        button : {
			styles: listStyle.button
		}
    }
    ....
}
```

The standard styles will through but the pseudo classes and/or stateful styles will not take effect.

**Comment by rofrischmann** [comment]
Thanks a lot! So happy people actually enjoy using Look.

Hmm, I think you're assigned it incorrectly. There're 2 possible options:

1. Using Babel you might have the `...` operator enabled. Therefore you could just do it this way:
```javascript
styles = {
   ...listStyle,
   /* All the other styles */
}
```

If you want to add some additional button styles to those added with `listStyle.button`, just go with this:
```javascript
styles = {
   button: {
       ...listStyle.button,
       /* Other button styles: Might overwrite listStyle.button */
   }
}
```

2. Why would you create another `styles` key within your `button` key? Probably you just need to use:
```javascript
styles = {
   button: listStyle.button,
   /* All the other styles */
}
```
And if you also want to use additional styles without the `...` operator, just use the `extend` mixin which enabled that for <=ES5:
```javascript
styles = {
   button: {
      extend: listStyle.button,
      /* Other button styles */ 
   }
}
```

@dnusca Hope that helped, if not: let me know again :)

**Comment by rofrischmann** [comment]
As mentioned above, this can be closed.
