### ISSUE TITLE
Possible to specify String as first argument to StyleSheet.create?

### ISSUE THREAD

**Issue by wyze** [rofrischmann/react-look#129]
This would solve issues when using multiple decorators that modify the `displayName` of the component. Since the `Component` is only used to grab the `displayName` for scoping styles, I think it is safe to accept a string here as well.

That way, I can generate the final display name of the component and send it to `StyleSheet.create` to have the correct scoping.

**Comment by rofrischmann** [comment]
Would awesome if you could test this :)

**Comment by wyze** [comment]
This is fixed with the latest commit! Thanks.
