### ISSUE TITLE
support the use of context in StyleSheet.create

### ISSUE THREAD

**Issue by talkhot** [rofrischmann/react-look#133]
Thanks for this great library! I'm currently testing and using Look for a project. The way you can use props and state is really handy I'm using context in my app to work with different themes. Do you think its a good idea to support the use of context as wel in StyleSheet.create? Context could be used as for example.

```javascript
color: (props, state, context) => context.theme.colors.text.contrast
```

**Comment by rofrischmann** [comment]
This seems totally legit :P I will add this later today.
And thanks a lot for those kind words!

**Comment by rofrischmann** [comment]
This will be added with the next release in arround 4 days :P

**Comment by nelix** [comment]
This is really awesome, thinking I might jump into react-look now (atm I am using radium and react-theme to do something much like this).
