### ISSUE TITLE
globalStyleSheet server-side support

### ISSUE THREAD

**Issue by MaxSvargal** [rofrischmann/react-look#139]
https://github.com/rofrischmann/react-look/blob/master/src/utils/globalStyleSheet.js#L5
Throws the ReferenceError: document is not defined. Server-side render doesn't work.

**Comment by rofrischmann** [comment]
Hey @MaxSvargal,
Thanks for reporting!

I am not quite into server-side rendering. Do you perhaps have an idea how we could solve this?
To enable the CSS polyfills we need the global StyleSheet and therefore we need to apply the `<style></style>`-tag to the client's document.
