### ISSUE TITLE
Combining Look and Inline styles causes media queries not to work

### ISSUE THREAD

**Issue by rickdoesburg** [rofrischmann/react-look#157]
```javascript
<div look={styles.topActivity} style={{backgroundImage: 'url(' + activity.image + ')'}} key={i}>
    <div look={styles.topActivityContent}>
        <h2 look={styles.topActivityTitle}><a href="/">{activity.name}</a></h2>
        <p look={styles.topActivityDescription}>{activity.description}</p>
    </div>
 </div>
```

```javascript
	topActivity: {
		borderRadius: '3px',
		width: '100%',
		position: 'relative',
		overflow: 'hidden',
		height: '200px',
		marginBottom: 20,

		backgroundRepeat: 'no-repeat',
		backgroundPosition: 'center center',
		backgroundAttachment: 'scroll',
		backgroundSize: 'cover',

		'@media (min-width: 992px)': {
			width: '19%',
			height: '400px',
		}
	},
```

will return (notice the object Object)

```HTML
<div style="
border-radius:3px;
width:100%;
position:relative;
overflow:hidden;
height:200px;
margin-bottom:20px;
background-repeat:no-repeat;
background-position:center center;
background-attachment:scroll;
background-size:cover;
@media (min-width: 992px):[object Object];
background-image:url(/static/img.jpg);">
```

**Comment by rofrischmann** [comment]
Thanks for noticing @rickdoesburg 
I will fix this directly today. My Object.assign seems not to work for deeply nested objects. Will use `object-assign-deep` instead.

**Comment by rickdoesburg** [comment]
Awesome!

**Comment by rickdoesburg** [comment]
I am not 100% percent sure, but it looks like extending some styles  (...buttons.Btn,) that have a media query OR :hover cause the same problem!

**Comment by rofrischmann** [comment]
Oh wait, did you configure Look to support media queries? Perhaps I should add this directly in front of the usage on the README. react-look ships without any plugins and mixins to have maximum configuration freedom. See [https://github.com/rofrischmann/react-look#configuration](https://github.com/rofrischmann/react-look#configuration)

You might add the provided react-dom preset to use every feature :P

**Comment by rickdoesburg** [comment]
I use the Presets['react-dom'] from react-look/addons and have lookRoot: true as property on the root component.

The first div inside the root component has lookConfig set.

render() { return (<div lookConfig={lookConfig}>...</div>);

I am receiving another warning:

Warning: Unsupported style property @media (min-width: 768px). Did you mean @media (minWidth: 768px)?

Changing the media query does remove the warning but the query doesn't work.

**Comment by rofrischmann** [comment]
Oh, I am sorry to think you left that. Well that error is coming from React directly, but I will check this later.   Show [object Object] somehow means pseudos and media do not get resolved at all, so something must be wrong with the preset (which is weird as I am including it within the examples myself)

**Comment by rofrischmann** [comment]
So you got your root Component like this: `Look(App, {lookRoot: true})` right?
And within the render you've set lookConfig e.g. `render() { return <div lookConfig={...}>...</div>}`

Could you please try to set the lookConfig when rendering your root Component? e.g.
`ReactDOM.render(<App lookConfig={...} />, document.body)`

This should do the magic for now, but I will check why it does not take configuration from outer DOM elements.

**Comment by rickdoesburg** [comment]
Thanks for the response. I will look into this tonight or tomorrow! I'll get back to you asap.

**Comment by paulscheltema** [comment]
I have implemented your changes, and it works now. Thank you very much. I thought we tried setting it at the root node, but apparently we did it the wrong way.

**Comment by rofrischmann** [comment]
You're welcome! Actually assigning the config to an inner-render node causes the config to only work for this very special node. It is recommended to always configure the top-level-component while rendering itself.

I guess I can close this one. Reopen if you still got some probs.
