### ISSUE TITLE
Using Look styling on react-router Link does not work properly

### ISSUE THREAD

**Issue by paulscheltema** [rofrischmann/react-look#158]
When using a look={...} style on a Link of react-router the underlying a tag gets the styles applied, however the mediaqueries and hover does not work.

Do you perhaps have an idea as to why it does not work?

**Comment by rofrischmann** [comment]
I found out that the [Link Component](https://github.com/rackt/react-router/blob/master/modules/Link.js) itself modifies the styles and classNames within its own render method, but that should still not crash media queries... I have never used the Link component by now, but this is kind of strange. Have you tried wrapping up the Component by another Component and assigning the styles to the outer one?

**Comment by paulscheltema** [comment]
Thank you for the response, the Link component shallow copies the style attribute, flattening the object values to string. Replacing the Link component with a deep copy works fine.

**Comment by rofrischmann** [comment]
Ah great to know. I will add something to the documentation, as there are plenty Components that do such things. It s not only limited to the Link Component. Therefore I will close this one as it has nothing specific to do with Look.
