### ISSUE TITLE
Using an array of children with length of 0 or 1 fails when the parent has a look style set

### ISSUE THREAD

**Issue by paulscheltema** [rofrischmann/react-look#159]
```
class Test extends Component {
  renderChildren() {
    let children = [1,2,3];
    return children.map(function (child) {
      return <div look={styles.child} key={child}>{child}</div>
    });
  }
  render() {
    return <div look={styles.parent}>{this.renderChildren()}</div>
  }
}
```

the above works, however when you reduce the list to ```let children = [1];``` or to ```let children = [];``` it fails.

when I remove the lines:
```
    if (_react.Children.count(children) === 1) {
      return resolveStyles(Component, _react.Children.only(children), config, parent);
    }
```
from ```react-look/lib/core/resolve.js``` line 170~173 (version 0.7.0)
it works. I do not know what those lines are for so I didnt create a pull request for this change.

Please look into it.

**Comment by rofrischmann** [comment]
I really appreciate your detailed issues! Makes it quite easy to understand the problem and quickly find a solution. Right now I am on my way back home from a concert, but I will check all your probs tomorrow. Kinda got an idea what causes both issues :)

**Comment by paulscheltema** [comment]
Really appreciate that.
