### ISSUE TITLE
unique style per child when dynamicly generating them fails

### ISSUE THREAD

**Issue by paulscheltema** [rofrischmann/react-look#160]
```
class Test extends Component {
  renderItem(i) {
    const colors = ['red, 'green', 'orange'];
    return (
      <div key={i}>
        <span look={styles.test} style={{color: colors[i]}}>we are the same color</span>
      </div>
  }
  render() {
    let items = [0,1,2];
    return (
      <div>
        {items.map(this.renderItem)}
      </div>
    )
  }
}
```

Expected:
3 lines in 3 different colors

Actual:
3 lines with the same color (last one used, orange in this case)

Removing the look={..} part will render the items in 3 diferent colors, as expected

I am guessing since it is the same dom element that gets assigned the style only the last one is applied. This is probably a closure capturing the values and nog checking the current value.

Do you have an idea how to fix this?

**Comment by rofrischmann** [comment]
I will check that tomorrow. Had no time till now :/

**Comment by rofrischmann** [comment]
One option would be to use stateful styles for now. e.g.
```styles = ... {
    color: (props) => colors[props.colorIndex]
}

// combined with
return <span look={styles.test} colorIndex={i}>we all have different colors</span>
```
I recommend not using a `style`-tag at all, but I will check that issue right after dinner.
