### ISSUE TITLE
hover states requiring a key or ref when used

### ISSUE THREAD

**Issue by paulscheltema** [rofrischmann/react-look#162]
create a div and give it 2 children with a hover style, do not give the children a key or ref attribute and they will both hover at the same time when hovering one of them.

expected this to just work, for now i will add a key to all elements that require hover styling.

**Comment by rofrischmann** [comment]
Seems that I removed that sign from the documentation, but yes. `:hover`, `:focus`, `:active` and all child-index pseudos `:first-child`, `:nth-child`, `:first-of-type`, ... all require a key or a ref. Also input validation pseudos such as `:valid`, `:in-range`, ... will especially need a ref to work.

I will add this to the documentation to clear that :P
