### ISSUE TITLE
Use 'look' instead of 'Look' as it is a HOC not a Class

### ISSUE THREAD

**Issue by oliviertassinari** [rofrischmann/react-look#167]
I ended up using
```js
import look, {StyleSheet} from 'react-look';
````
instead of 
```js
import Look, {StyleSheet} from 'react-look';
```
Because, I'm enforcing some eslint rules:
I had an error when doing
```js
export default Look(Component);
```

`A function with a name starting with an uppercase letter should only be used as a constructor  new-cap`
(http://eslint.org/docs/rules/new-cap.html)

Would you consider migrating from an uppercase to a lowercase in the documentation?
For instance, `react-redux` is using `connect()`.

**Comment by rofrischmann** [comment]
Let me have some time to think about why I ever used a uppercase there. But sure you're right, we could have everything migrated, but that's quite a bit of work replacing it everywhere within code blocks while others remain uppercase. Feel free to have a PR ;)

**Comment by oliviertassinari** [comment]
> Let me have some time to think about why I ever used a uppercase there.

May be because `Radium` do.

> Feel free to have a PR

Yes, I was thinking about this. But I haven't decided yet which solution I will use for styling my components :grin:.

**Comment by rofrischmann** [comment]
@oliviertassinari Have you thought about it? For me it makes sense to rename everything.. I am right now just about to reach a milestone at another projects, will have time for Look again next week!
