### ISSUE TITLE
react-transform-hmr

### ISSUE THREAD

**Issue by oliviertassinari** [rofrischmann/react-look#168]
The hot reloading feature doesn't work with HOC look component.
I get the following error when a do any update on one of my components.
```
TypeError: Cannot read property '__reactAutoBindMap' of undefined
```

**Comment by rofrischmann** [comment]
Hmm, I actually never used react-transform before. I could check their docs in order to know what prevents the auto binding. Maybe it's because I use a map to store browser state information... Could move that to a good old plain object if it helps

**Comment by oliviertassinari** [comment]
That some interesting stuff https://github.com/FormidableLabs/radium/pull/255

**Comment by rofrischmann** [comment]
Woot. Interessting. I will check that after lunch :)

**Comment by rofrischmann** [comment]
Pushed the fix, will update tomorrow :)

**Comment by oliviertassinari** [comment]
@rofrischmann Thanks.
