### ISSUE TITLE
React Native: Requiring unknown module "react". If you are sure the module is there, try restarting the packager.

### ISSUE THREAD

**Issue by andycaramba** [rofrischmann/react-look#170]
Hi. I'm trying to use Look with React Native and has issue described in title.

Below is some simplified code i've used
```javascript
import React, { View } from 'react-native';
import Look, { StyleSheet } from 'react-look';

class MyComponent extends React.Component {
    render() {
        return (
            <View look={styles.container}>
            </View>
        )
    }
}

const styles = StyleSheet.create(MyComponent, {
    container: {
        flex: 1
    }
});

export default Look(MyComponent);
```

```
"react-look": "^0.7.1"
"react-native": "^0.17.0"
```

**Comment by rofrischmann** [comment]
Oh, got that issue. I thought react-native would install react by default as it is build on it? Could you please just "try" to `npm install react` would like to see what happens actually.
If not I might have to use different packages again as I had Look working with react-native before.

**Comment by andycaramba** [comment]
I think this issue is corresponding with https://github.com/facebook/react-native/issues/2985
I'll try to wait RN0.18 for few days. 
Thanks.

**Comment by rofrischmann** [comment]
Thanks for refering. After all I will soon refactor the code base and and packaging to allow better usage with RN anyways. Hope you can fix the issue right now :)

**Comment by rofrischmann** [comment]
@andycaramba Are you fine if I close this issue? (at least for now, as it seems its not an issue with Look itself rightß)

**Comment by andycaramba** [comment]
Yes, i'm fine. I have some time and I'll wait RN team for 0.18 release. Thank you.

**Comment by rofrischmann** [comment]
Great! Come back creating an issue if there's anything not working as expected with 0.18 soon. You're welcome :)

**Comment by rohan9** [comment]
same problem but with the toast

**Comment by rohan9** [comment]
error eith the restart the packager or runing npm install
