### ISSUE TITLE
[benchmark] Rendering performance with inline styles vs. CSS

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/react-look#174]
'd be nice to have 2 different examples which feature both inline styles and CSS. 

- [x] complex app with a lot different components and only a small amount of duplication *(e.g. current demo examples)*
- [x] simple app with fewer components but high amount of duplication *(e.g. ListView with tons of ListItems)*

**Comment by rofrischmann** [comment]
I did a huge performance case-check and tried tons of improvements, variations, etc.
Will provide proper information soon!

**Comment by arbesfeld** [comment]
Excited to see this!

**Comment by rofrischmann** [comment]
@arbesfeld I hope I get it ordered somehow soon. Was quite a lot stuff (mostly small variations I tried).
Yet there really are some extreme cases where inline styles actually totally suck. 
e.g. if you're having a list of 1000 elements each wrapped with Look to resolve just a basic set of styles (basically no mixins or just simple pseudo classes). It does the same thing over and over again for exact 1000 times...

But I surprise, I wouldn't have done that if not for improving the API. I am hoping for huge improvements soon. I am sure to blog about it as well.
