### ISSUE TITLE
[Feature] Component Queries based on Component size

### ISSUE THREAD

**Issue by dustin-H** [rofrischmann/react-look#189]
Hi there,

it would be nice to do a mediaquery based on the offsetWidth/offsetHeight of a referred parent dom-element.

Cheers
Dustin

**Comment by rofrischmann** [comment]
This would be an easy one if @soprano's vision of "Layout in React" will be implemented one day.
Let's for now wait until this (might) happen and reopen this issue, because as is now there is no good solution to this without rerendering.
