### ISSUE TITLE
contextTypes is not working with react-router-redux 

### ISSUE THREAD

**Issue by tarkanlar** [rofrischmann/react-look#190]
When i use look with 'react-router-redux',  I can't get the router context type.
I am not sure if i am doing some thing wrong or there is an issue.

```js 
export default connect(select, bindActions)(look(RightTab));
```

**Comment by rofrischmann** [comment]
Could provide a full example Component? I've not used react-router until now :p I am sure to find the problem. We should probably add it to FAQ's afterwards.

**Comment by tarkanlar** [comment]
I just simplified the component but something like this 
```js
import React, { Component, PropTypes } from 'react';
import { routeActions } from 'react-router-redux';
import { connect } from 'react-redux';
import look, { StyleSheet } from 'react-look'


class Chat extends Component {
  render() {
    console.log(this.context.router);
    return (
        <div style={ styles.container }>
        Hello
        </div>
    );
  }
}


Chat.contextTypes = {
  router: PropTypes.object
};


const styles = StyleSheet.create(Chat, { 
  container: {
    color: 'red'
  }
}
function select(state) {
  return {
    user: state.auth.user
  };
}



export default connect(select, null)(look(Chat));
```

**Comment by tarkanlar** [comment]
Thanks @rofrischmann can you please update the version for npm?

**Comment by rofrischmann** [comment]
I will do soon as the api is ready, for now u could just fix that within ur node modules to be able to work with it :p
