### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/react-look#195]
As mentioned in #193, React Native is not supported in Look 1.0.0-Beta1 yet. This is cause of drastic changes in the core to get a performant and simple react-dom version first. We should now focus on abstraction to get the Native support as it was before in 0.7.2.

As my tests turned out, the core difference is basically just the resolver. We need to have a way to actually "apply" a resolver onto the enhancer itself.

Also the  `<StyleRoot>` Component must be switched completely as it basically does just one job: Pass the config down.
Instead of `className` we should use `style` directly.

## Todo
- [x] Native resolver (listening to `style` instead of `className`)
- [x] Native `<StyleRoot>`

## Package
As there's stuff we can't bundle with the DOM-version, we should separate 2 dedicated npm modules for both plattforms. 
- [x] 2 packages

**Comment by rofrischmann** [comment]
@ericmuyser Perhaps you can help me out.. I am trying to create a React Native example located in demo/native. I can get the packager to start out of the root folder, but build the demo/native app. It should still be able to require files from modules. The whole process is kind of a mess I do not quite get yet. I'd like to use 0.20.0-rc1 as I had hug problems getting 0.19 running at all which was caused by the .babelrc I guess, but placing a custom .babelrc next to the index.ios.js, ... didn't help either...

**Comment by ericmuyser** [comment]
@rofrischmann Hey I'd love to help if I can!

I'm in a bit of a pickle though. I've love to upgrade, but I also want to get stuff done. I'm not inclined to jump to 0.20.0-rc1 without being confident it's worthwhile. For that, I need to know you're not going to let native support fall again, then I'm down to give it serious effort :) This allows you progressively enhance existing React Native code, and use it on web too. That's not something any other library does AFAIK. Most native components are just using StyleSheet. If people can easily enhance them, that's a huge bonus. If it compiles on web, that's also a huge bonus. I have a tendency to build efficiency from the lowest common denominator - that's native, because it lacks support for full CSS.

**Comment by rofrischmann** [comment]
@ericmuyser Sounds great that you'd like to help. Actually I guess I got a working version for React Native already, but I was not able to build an example which requires the modules from the parent folders. Already tried `--root ../../modules`. 
For now I will test it by publishing with a special tag, but that seems not to be the best solution. 
I think the API for Native is not quite different, but we need to do some stuff different so you're not just able to use the exact same Component on both native and web right now.

Instead of using `className` we should use `style` as Native does not have className at all. Also `LookRoot` and the `look` wrapper are different. Defining styles will easily be done using the build-in `StyleSheet` which react-native already provides.

If you got any ideas to even do this better let me know :P We could also have a chat if you'd like to.

**Comment by rofrischmann** [comment]
@ericmuyser Feel free to check that branch out (`react-native`) The API is the same as the DOM version except that you import `StyleSheet` and `LookRoot` from `{ Native }`.
So basically do: `import look, { Native: { StyleSheet, LookRoot }} from 'react-look'`
Also one should use `Presets['react-native']` instead of `Presets['react-dom']` which ofc should be clear.

I was still not able to get a running example inside *demo/native* which could be started from the root folder and imports files from the roots modules as well.

**Comment by ericmuyser** [comment]
Hey nice @rofrischmann 
I didn't have a chance to do much coding this weekend. I'll give it a shot this week, and push any fixes/examples I come up with.

Cheers!
