### ISSUE TITLE
Add class to DOM before element gets rendered

### ISSUE THREAD

**Issue by dustin-H** [rofrischmann/react-look#202]
The class of a dynamic style seems to be added after the element has been rendered. This leads to not working css animations at the first time.

**Comment by rofrischmann** [comment]
Seems to be caused by asynchronously adding those classNames to the DOM **after** the whole React tree was rendered.
I was already thinking of some way to directly use insertRule within the resolver. But not sure if that totally fixes the problem is unknown.
