### ISSUE TITLE
Native: missing dependency

### ISSUE THREAD

**Issue by oliviertassinari** [rofrischmann/react-look#214]
I'm having the following error:

> ERROR in ./~/react-look-native/lib/core/native/resolver.js
Module not found: Error: Cannot resolve module 'shallowequal' in /Users/oliviertassinari/material-ui/docs/node_modules/react-look-native/lib/core/native
 @ ./~/react-look-native/lib/core/native/resolver.js 15:20-43

Running: `npm install shallowequal` fix this.

**Comment by rofrischmann** [comment]
Oh damn yeah. I see the dependency is missing. I somehow see this issue quite often. I always run `--save-dev` but it does not update the package.json...
I will fix that with the next release. Thank you!

**Comment by oliviertassinari** [comment]
Awesome, thanks. I was playing with the react native version of material-ui.

I'm looking for a way to use the context to style the components. I have tried to use the following on a stateless functionnal component without luck. Any idea?
```js
const styles = StyleSheet.create({
  root: {
    height: 48,
    flex: 0,
    justifyContent: 'center',
    backgroundColor: '#fff', // To show the box sizing
  },
  welcome: {
    fontWeight: '500',
    paddingLeft: 16,
    textAlignVertical: 'center',
    fontSize: 14,
    color: (prop, state, context) => {
      return 'rgba(0, 0, 0, 0.54)';
   }, 
  },
});
```

**Comment by rofrischmann** [comment]
I will upload my React Native test example soon which should also include that use case. But what exactly is not working?

**Comment by oliviertassinari** [comment]
> But what exactly is not working?

The text is no longer visible but that's an other issue. I will open a new issue if I can't fix it.

**Comment by rofrischmann** [comment]
Yeah ofc, feel free to! I am not that skilled with React Native anyway so I never had the chance to test every feature in deep. Also feel free to contact me via Twitter PM or sth. similar if you got other questions

**Comment by oliviertassinari** [comment]
Thanks for you support!

**Comment by oliviertassinari** [comment]
regarding the second issue, turns out, I wasn't using the `look` HOC. Oops :grin:.

**Comment by rofrischmann** [comment]
Ok create, so adding the dep closes this one?

**Comment by oliviertassinari** [comment]
Adding the dependency solve the bundling issue, yes.
