### ISSUE TITLE
Support for stateless functionnal component

### ISSUE THREAD

**Issue by oliviertassinari** [rofrischmann/react-look#215]
As far as I have *looked* at the documentation and tested it, stateless functional component are not supported.
Do you have any plan on this and if not, how hard would it be to support it?

**Comment by rofrischmann** [comment]
Actually they are "supported" by transforming into ES2015 classes (e.g. the Media-Component within the demo).
I've never really tried to get those pure functions ready at all, but I can give it try tomorrow. I guess prop/context related stuff should not be too hard to implement. But as some plugins/mixins use the state also, they would probably fail running.
I'll try to do some research on that.

**Comment by alitaheri** [comment]
I think when using function components we need a LOT less logic as we don't have to take state into account. I'll try to figure out if this is possible, we might have issues with contexTypes. But that's resolvable.

**Comment by rofrischmann** [comment]
I will now do some experiments with stateless functions and how to handle possible errors :+1:

**Comment by rofrischmann** [comment]
@oliviertassinari @alitaheri FYI implemented this and got evrything working locally. Just need internet connection to push it :p
