### ISSUE TITLE
Native : LookRoot change the layout.

### ISSUE THREAD

**Issue by oliviertassinari** [rofrischmann/react-look#217]
Adding the `<LookRoot />` change the layout of the screen.
Here is the diff:
```diff
const Container = () => (
+  <LookRoot config={config}>
     <App />
+  </LookRoot>
);
```

Here is the `<App />`:
```jsx
import React from 'react-native';

const {
  StyleSheet,
  Text,
  View,
} = React;

class App extends React.Component {
  render() {
    return (
      <View style={styles.root}>
        <Text style={styles.title}>
          Material-UI
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: '#F5FCFF',
  },
  title: {
    paddingTop: 15,
    margin: 20,
    fontSize: 20,
    textAlign: 'center',
  },
});

export default App;
````
**Before:**
![capture d ecran 2016-02-28 a 21 37 43](https://cloud.githubusercontent.com/assets/3165635/13381728/87a9c62a-de63-11e5-8260-30544b8562e8.png)

**After:**
![capture d ecran 2016-02-28 a 21 37 16](https://cloud.githubusercontent.com/assets/3165635/13381722/786bd9c8-de63-11e5-8415-f6fbda492054.png)

**Comment by rofrischmann** [comment]
Checkout [LookRoot.md](https://github.com/rofrischmann/react-look/blob/develop/docs/native/api/LookRoot.md#props). You may also pass a `style` prop to LookRoot which should fix that issue.

**Comment by alitaheri** [comment]
@oliviertassinari It's probably this guy: https://github.com/rofrischmann/react-look/blob/develop/modules/api/dom/LookRoot.js#L27,

@rofrischmann Do you think there is a chance we can somehow avoid rendering a div there? but nevermind my comment I'm still trying to learn, I'll get back to you when I figure out a way we can remove that extra div :+1:

**Comment by rofrischmann** [comment]
@alitaheri I am not quite sure if it's possible to pass down some context without an extra one, but it shouldn't be a problem either as you only do that once. Also it's the native version @oliviertassinari was using, so there's no div but a View :P

**Comment by alitaheri** [comment]
@rofrischmann Actually you don't need a div to pass down context. you can just:

```js
render() {
  return this.props.children;
}
```

So if we can somehow move the logic from [StyleComponent](https://github.com/rofrischmann/react-look/blob/develop/modules/api/dom/LookRoot.js#L41) We might be able to avoid that extra div/View. react does have some methods that allow you to render a subtree somewhere else. so we can put the `<style/>` somewhere else, like append it to `body` or `head` or it's equivalent native place. I don't know how react-native works :grin:

**Comment by rofrischmann** [comment]
Oh hah I did not know that actually. So we can leave it for Native and for DOM we might be able to do the same. Actually the StyleComponent is only used for DOM as Native does not have CSS styles at all :P
I already thought about having a style within the head, but that would perhaps issue with server-side rendering.

**Comment by alitaheri** [comment]
Well if the css is not `scoped` it should be inside the head as HTML says. I need to investigate further.

configs can be passed down very easily, take a look at https://github.com/acdlite/recompose/blob/master/src/packages/recompose/withContext.js you can use this with 3 lines of code to pass down what you need.

**Comment by oliviertassinari** [comment]
> We might be able to avoid that extra div/View

That sounds far better than adding a style property to change the layout.

**Comment by rofrischmann** [comment]
Feel free to pull request that for the native version (Otherwise I'll do it tomorrow). For the DOM I need to figure out how to add the <style> somewhere else but I already got an idea for that.
Need to go to bed now as university starts early tomorrow :sleeping:

**Comment by rofrischmann** [comment]
#220 will fix this issue and move the `<style>` to the head :)
