### ISSUE TITLE
Consider extracting react-look-native into a new repository

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/react-look#219]
Right now we should consider if splitting the repos into two separate would make sense at all. 
Most docs are different as well as almost every mixin/plugin and even the resolver. 
Only some utils/mixins/plugins/core parts are shared at all. (We might add a third repo which provides this shared stuff)

**Comment by alitaheri** [comment]
I would recommend different directory structure over different repo ( move everything into packages ) I have 2 reasons for that:

1. Most issues are related to both, although they need different changes, but they both still need to be maintained along side one another.
1. Scattered PRs, no single PR will be able to address a single issue for both versions.

You don't need another repo just to maintain some common codes just another folder really. you can have:

```
src/
-- react-look
-- react-look-native
-- common
```

something like that :sweat_smile: 

You should also separate the docs for these two.

You can have a third repo for the common stuff but only if they provide value independently. I mean can someone use them while not using react-look? is it orthogonal or reusable enough?

**Comment by rofrischmann** [comment]
Hmm. I get what you're telling. I was just thinking about it again and thought about just extracting the native code to a new repository which imports all the stuff from the main repo so we do not need to have to use a third one for shared code.

I think this would be easier to understand both the code and the docs.
I don't know if issues generally apply to both repos, but I don't think that would happen often actually.

For now thanks for your ideas. Let's think about that the next days. Do not want to shoot something too fast actually :P

**Comment by alitaheri** [comment]
> For now thanks for your ideas. Let's think about that the next days. Do not want to shoot something too fast actually :P

I completely agree :+1: It's always great to discuss something with others before coming to conclusions :+1:

**Comment by rofrischmann** [comment]
I've sleep over it and now think the folder architecture is actually better than splitting the packages.
The initial README should directly point to the right package README and nothing more. 
We should also add Contributing.md as well as Issue and PR templates :)

**Comment by alitaheri** [comment]
You could also try importing only the things you from lodash too, that will also decrease the bundle size a lot :+1: 

```js
import * as merge from 'lodash/merge';
```

instead of `_.merge`

**Comment by rofrischmann** [comment]
Yeah I was using [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) which did this automatically while transpiling the code, but it somehow failed to do it at exactly 1 position :/

**Comment by alitaheri** [comment]
I see O.o But I saw it all in there. so I guess we should open an issue there :sweat_smile:

**Comment by rofrischmann** [comment]
Hehe yep, I actually was just to lazy last time. Also I could not really reproduce that case, but you might add it locally and test it.

**Comment by rofrischmann** [comment]
I will close this one and create an actual task.
