### ISSUE TITLE
Stateful selectors

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/react-look#221]
As proposed by @chrismcv [here](https://github.com/callemall/material-ui/pull/3248#issuecomment-189955931) it would be awesome to have stateful selectors in addition to stateful values.

e.g. 
```javascript
const styles = StyleSheet.create({
   box: (props, state, context) => {
      return {
         color: props.color,
         backgroundColor: context.theme.bgColor
      }
   }
})
```

**Comment by rofrischmann** [comment]
@chrismcv #222 will soon add stateful selector support :) Wait for beta5 and you may use it.

**Comment by chrismcv** [comment]
awesome - thanks @rofrischmann :+1:
