### ISSUE TITLE
Ability to export css as string for server rendering

### ISSUE THREAD

**Issue by dustin-H** [rofrischmann/react-look#233]
Hi there,

it would be nice to be able to export all styles as css string after i rendered the app on the server.

With this feature I would be able to fulfill the requirements of [amphtml](https://github.com/ampproject/amphtml): Only one style tag in the html-head.

Any plans?

Cheers
Dustin

**Comment by rofrischmann** [comment]
Seems legit. I would suggest sth. like `StyleSheet.renderToString` to do this. Would be in sync with React's API.

**Comment by dustin-H** [comment]
+1

**Comment by alitaheri** [comment]
+1 That can also be used to write unit tests :+1: :+1:

**Comment by alitaheri** [comment]
@rofrischmann You are a machine O.O >.< 0101 :computer:
