### ISSUE TITLE
Automate project initialization and resource sharing

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/react-look#235]
**Environment**: Both
**Type**: Infrastructure

-------------------
#### Description
Right now both packages depend on the common files which get imported with relative links <br>
e.g. `../../../common/modules/core/enhancer`<br>
This is not only hard to read and manage, but also complicates the bundling and release process as those common files would be missing later on.

We should provide scripts that automatically copies those files to every package.
Also we are using same test setup / mocha.opts within every package (except the native compiler for React Native). We should share those as well.

**Comment by philpl** [comment]
@rofrischmann You could do some bundling with webpack? That way you'd simplify both the bundling/release process and you could add some aliases that simplify the import statements.
