### ISSUE TITLE
Separate prefixer and provide an extendable interface

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/react-look#237]
**Environment**: React
**Type**: Feature Request

-------------------
#### Description
We should separate the prefixer from the plugins array. It should be a unique key within the config so we could use it directly within all components that perhaps need to do some prefixing too (e.g. the StyleContainer).

Perhaps we should also provide an interface which can be extended, so the prefixer actually is an instance and not just a pure function which actually has all the functions we need to use.

**Proposal (Code Example)** 
```javascript
class Prefixer {
   constructor() {
       // any constructor stuff e.g. setting the userAgent
   }

   prefix(styles) {
       return styles
   }

   getKeyframePrefix() {
      return [] // e.g. ['-webkit-', '-moz-'] to add both prefixes
   }
}
```

**Comment by alitaheri** [comment]
Is there anything other than setting `userAgent` than can go into the constructor? If that's the only case, then I think this will only add complexity. userAgent is a string most of the time. it can be serialized, equated, etc... But an instance can never have those in a safe manner.

**Comment by rofrischmann** [comment]
Well actually I do not know. The both prefixer I build actually only take in the userAgent (the static one does not even take in anything), but you should have something extendable for people who perhaps want to build their own prefixer, without breaking functionality. Perhaps we can also engrave sth. like `_isLookPrefixer`, to be sure its working. I do not know if it's overload, but right now I really struggle to support both prefixers separately and we at least need those 2 methods pointed out above.

**Comment by rofrischmann** [comment]
I think for now we might just use the userAgent? I do not know much about other prefixing libraries or if there are some actually.

**Comment by alitaheri** [comment]
> but you should have something extendable for people who perhaps want to build their own prefixer

Well then I think we should make react-look plugable enough so people can inject their or transformers, at material-ui we have 2 important transformers, one is your prefixer the other is rtl support, also a callOnce that ensures the style is only transformed once. So it would be awesome if we could have the same here too. I mean it's not only prefixing people might also like to have other transformers too. So I think you shouldn't bother improving this part of your code as other people can simply get it and create their own from and plug it back to react-look.

**Comment by rofrischmann** [comment]
What do you actually think of a transformer to do? Because you already have great plugin abilities to basically do anything you'd like to right now.

For me the prefixer really is some kind of special case, because it is the only plugin which is used separately within the `StyleContainer`, so you'd make sure this works actually.

**Comment by alitaheri** [comment]
Well what i mean is if we treat the prefixer as just another ( removable, addable ) plugin then it's not necessary to enhance the prefixer and others can implement their own if they want more functionality. Some might also not want prefixer at all. it's boils down to more bytes with server-side rendering. so it should be disabled. Many don't want to support older browser simply because they can tell their users to use a modern one.

**Comment by rofrischmann** [comment]
Oh yeah, ofc you still can choose which or even if at all you would like to have a prefixer. And also this instance should just implement the basic minimum what a prefixer needs so no module will fail actually.
But the problem is if it is just another plugin within the plugins array how do you actually "get" it to use it within the StyleContainer, where you actually need to use at least the same as the dynamic styles need.

If there's no prefixer passed that's just fine and it won't do any prefixing.
I think I can create a short example soon, which maybe points out why I already want to have sth. like this. For my private projects I recently switched from inline-style-prefixer to inline-style-prefix-all (which is basically just a really small (3kb gzipped) version of inline-style-prefixer's static `prefixAll`, but the StyleContainer still uses inline-style-prefixer.

**Comment by alitaheri** [comment]
Hmmm, you've got a point there... if it's instance it's going to be easier to add and remove. :+1: We solved it with factory functions though: https://github.com/callemall/material-ui/tree/master/src/styles/transformers. might not be a bad idea to take a look :+1:

**Comment by rofrischmann** [comment]
Alright yeah. Seems like basically the same idea, the current plugins are doing it as well.
e.g. https://github.com/rofrischmann/react-look/blob/develop/packages/react-look/modules/plugins/prefixer.js
It basically is just a method which gets in all the relevant data and returns a new styles object.
This is almost always just enough, but I guess perhaps the prefixer really is some kind of special here, but thanks for pointing out! I will now try to play with it a bit.

**Comment by alitaheri** [comment]
Yeah it's special indeed :laughing: Good job :+1: :+1:

**Comment by rofrischmann** [comment]
Good either, I really like how you investigate time and comment everything. Makes it much easier to do a decision if there's someone helping and backing you :)

**Comment by alitaheri** [comment]
Well, we plan on using your awesome project, I want it to become even more awesome too :heart_eyes: :heart_eyes: I'm glad my comments are helpful :blush:
