### ISSUE TITLE
Overriding Bootstrap/other style library styles

### ISSUE THREAD

**Issue by skitterm** [rofrischmann/react-look#248]
**Version**: 1.0.0 (beta5)
**Environment**: React 
**Type**: General

I'd like to use React-look with Bootstrap. Unfortunately, bootstrap sometimes uses styles that have a higher specificity than just one class, like 
```css
.nav-bar .item {
  /* some styles here */
}
```

These are not override-able with a single generated css class. Do you have any ideas/solutions for overriding these with React-look? Aphrodite uses the <code>!important</code> command after each style, which may be overkill, but it does allow external styles to be overridden.

**Comment by rofrischmann** [comment]
Have you tried using StyleSheet.addCSS already? 
```javascript
StyleSheet.addCSS({
   '.nav-bar .item': { /* your styles */ }
})
```
This will add global CSS rules, but if they're somehow not override-able (or already use `!important`) this might not be solvable without `!important` at all.
You could use [inline-style-transformer](https://github.com/rofrischmann/inline-style-transformer)'s `importantify` to do this in a clean way, but it doesn't change the fact that you're using `!important`.

> Note: importantify is not documented right now, but should work as it is quite a simple operation.

I never used any third-party styling library, CSS framework or Bootstap itself, so I am sadly not aware how they define their styles.
