### ISSUE TITLE
React 15 Support

### ISSUE THREAD

**Issue by nathanmarks** [rofrischmann/react-look#254]
@rofrischmann Just a very quick question -- have you tried this out with react 15 yet?

**Version**: 1.0.0 (beta5)
**Environment**: React / React Native / Both
**Type**: General

**Comment by rofrischmann** [comment]
Hey @nathanmarks I am actually really busy and do not have time to test it, but I will hopefully find some time to check it tomorrow. But as far as I know it should "just" work as is. If you've already tried, feel free to tell if it works :P

**Comment by nevir** [comment]
So far I haven't encountered any problems with it

**Comment by nevir** [comment]
Ok, one problem; unsure if it's React 15 specific, though: https://github.com/rofrischmann/react-look/issues/257
