### ISSUE TITLE
Inheritance support for look()

### ISSUE THREAD

**Issue by nevir** [rofrischmann/react-look#258]
Currently it appears like subclasses of `look`-enhanced components do not get to enjoy any of its behavior.  

Would be pretty useful to cut down on boilerplate, particularly when you've got a base component class that adds other common functionality (and prevents you from going full-on stateless components)

**Comment by nevir** [comment]
Hmm, I can see how this would be a real pain to implement w/ how react-look currently wraps `render()`.

It also makes me wonder how perf is in larger component trees, given that you're (effectively) walking all elements.  (FWIW, we saw a dramatic perf hit via Radium doing similar things - though it was injecting `style` properties, not just `className`).

I wonder if it would make sense to calculate the static & dynamic classes during `componentWillMount` and `componentWillUpdate`?  That way the component can just pass all the `className`s straight through.  I'm not sure if the API there would be reasonable, though (for class-based components, maybe `this.styles` or `this.state.styles`.  But for stateless components ...???)

**Comment by rofrischmann** [comment]
Could you please fill out the predefined issue template as detailed as possible? I know it sometimes does not exactly match what you want to tell, but it helps me a lot to understand the problem.
Also please add a quick example as I do not really understand why this would be useful actually. (Note: I avoid inheritance as much as possible)

According your second comment: That quite a good idea actually. I will try to take this in consideration, while implementing a better enhancing and rendering method.

**Comment by nevir** [comment]
I'm actually going to drop the inheritance ask here, and jump on this API idea.  New issue incoming in a sec :P
