### ISSUE TITLE
Grouping the CSS classes

### ISSUE THREAD

**Issue by SMahil** [rofrischmann/react-look#261]
**Version**: 1.0.0 (beta5)
**Environment**: React / React Native / Both
**Type**: Bug / Feature / Infrastructure / Docs / General

-------------------
#### Description
How to do grouping of CSS Classes. For example in CSS:

h1,h2,h3,h4,h5,h6{
  line-height:1;
}
How to get this in react-look

**Comment by SMahil** [comment]
For more description:

in many cases we will be using same css. As i took the example of different headings, We need same line-height or same color. Rather than adding the same css to each and every heading tag, I want to group all these tag.
In CSS, we do like below:

h1, h2, h3{ ...  ..... }
OR

classname1, classname2{ ....   }

How can we get this output in React-Look

**Comment by rofrischmann** [comment]
Actually what you try to achieve is not what Look was designed for. Look is modular and Component- / element-based which means you do not style HTML-tags but single elements (without considering their tag-name at all). If you want to use the same style rule for two different elements, why would you even create another class if you can just use the same one again.

Still as it is a valid use case and often used in practice, you may define a static CSS sheet using the `StyleSheet.addCSS()` helper. It will automatically add all styles to the global stylesheet.
e.g.
```javascript
StyleSheet.addCSS({
   'h1, h2, h3, h4, h5, h6': {
      lineHeight: 1
   }
})
```
will add the following to your global stylesheet:
```CSS
h1, h2, h3, h4, h5, h6 {
   line-height: 1
}

I hope this cleared the usage and solved the problem. If not feel free to reopen the issue.

**Comment by SMahil** [comment]
Thanks for the help. :)

**Comment by SMahil** [comment]
Hi
I have another question

I want to create common css file for all the components like

*{
margin:0; padding:0;
}
body{
    background: #fff;
    color: #333;
    font: 400 13px/1.231 "Helvetica Neue",Helvetica,Arial,sans-serif;
}
h1, h2, h3, h4, h5, h6 {
   line-height: 1
}
 .... 
How can I import this for all the components so that CSS also becomes reusable.

Also How to save this file also
