### ISSUE TITLE
Duplicate <style> insertions with react-storybook

### ISSUE THREAD

**Issue by namuol** [rofrischmann/react-look#262]
**Version**: 1.0.0 (beta8)
**Environment**: React
**Type**: General

-------------------
#### Description
I'm using [Storybook](https://github.com/kadirahq/react-storybook) to iterate on my components, which are styled with react-look.

Here's what it looks like to write a "story", in this scenario:

```js
import { storiesOf } from '@kadira/storybook';

storiesOf('Combobox', Combobox)
  .add('is loading', () => (
    <LookRoot config={lookConfig}>
      <Combobox loading={true} />
    </LookRoot>
  ))
  .add('is loaded', () => (
    <LookRoot config={lookConfig}>
      <Combobox content={[{value: 42, text: 'Fourty Two'}]} />
    </LookRoot>
  ));
```

As you'd expect, `<LookRoot>` gets re-rendered entirely whenever I switch to a different story.

This quickly leads to many duplicate `<style>` tags in the `<head>` section of Storybook's preview iframe, all with the exact same ID (which suggests they're meant to be globally replaced).

Part of the problem is that `<LookRoot>` [doesn't check if the style element already exists](https://github.com/rofrischmann/react-look/blob/c1c55b902b0f9e7ee4f4389ad94513450e227867/packages/react-look/modules/api/LookRoot.js#L58-70), which seems like an easy thing to fix, but I don't have a complete picture of how this works.

What are your thoughts?

----

**Update**: A simple workaround is to manually create my own `<style id="my-custom-style-el">`, inject it into `<head>`, and then explicitly include `styleElementId: "my-custom-style-el"` in `lookConfig`.

Here's what that looks like:

```js
const STYLE_ID = '_react-look-storybook-stylesheet';

const style = document.createElement('style');
style.id = STYLE_ID;
document.head.appendChild(style);

const lookConfig = Presets['react-dom'];
lookConfig.styleElementId = STYLE_ID;
```

**Comment by rofrischmann** [comment]
As it seems you found out how to "reuse" the same <style> object. May I close this one? Or do you think Look should check for existing style tags by default. Seems legit somehow...

**Comment by namuol** [comment]
Yeah, I think it makes sense to always check that the `<style>` doesn't already exist before adding it -- I created a PR (#265) with the necessary changes
