### ISSUE TITLE
[Question] Window scroll plugin/mixin

### ISSUE THREAD

**Issue by nevir** [rofrischmann/react-look#263]
I'd be interested in building a plugin or mixin that allows you to update styles when a scroll event is emitted.  Would be handy for things like collapsing headers once you scroll down the page, etc.

Something like this:

```js
const MAX_HEIGHT = 100;
const MIN_HEIGHT = 50;

const styles = StyleSheet.create({
  root: {
    height: MAX_HEIGHT,
    '@scroll': offset => ({
      height: Math.max(MIN_HEIGHT, Math.min(MAX_HEIGHT - offset, MAX_HEIGHT)),
    }),
  },
});
```

However, it's not clear to me how I can achieve this via the current API (I'm not sure how I can cause the element to re-render) - curious if you have any pointers!

**Comment by rofrischmann** [comment]
There's the [`newProps._lookShouldUpdate = true`](https://github.com/rofrischmann/react-look/blob/develop/packages/react-look/docs/guides/customPlugin.md#_lookshouldupdate) flag which can be to force rerendering. 
> Note that you'd want to use the Mixin plugin **before** the **statefulValue** plugin or else the `offset => ({})` will be resolved as a stateful value where `offset` would reference `props`.

**Comment by rofrischmann** [comment]
I will close this one as it should be answered actually.
