### ISSUE TITLE
PeerDependencies warning with react v15+

### ISSUE THREAD

**Issue by wesleycoder** [rofrischmann/react-look#266]
**Version**: 1.0.0 (beta8)
**Environment**: React
**Type**: General

-------------------
#### Description
PeerDependencies on `react` and `react-dom` are awkward, I'm having the folowing message:

    npm WARN react-look@1.0.0-beta8 requires a peer of react@^0.14.3 but none was installed.
    npm WARN react-look@1.0.0-beta8 requires a peer of react-dom@^0.14.3 but none was installed.

My dependencies are as below:
`package.json`:

      [...]
      "dependencies": {
        [...]
        "react": "^15.0.1",
        "react-dom": "^15.0.1",
        "react-look": "^1.0.0-beta8",
        [...]
      },
      [...]

With this `npm ls` fails and I had to workaround my pre-commit hook to bypass this...

**Comment by wesleycoder** [comment]
I think we shoud use the peer-dependencie, like: `react@^0.14.3 || ^15.0.0`

**Comment by rofrischmann** [comment]
Hey @wesleycoder, this has already been done as you can see [here](https://github.com/rofrischmann/react-look/pull/256/commits/7aa7bc7e37e7f637f60adb58a07bc6a37a4efc61). I am short of time right now and not able to push a new version without doing my usual checks first. 
I hope to be more responsible soon. Full 15+ support is at the top of my To-Do list for Look.

**Comment by wesleycoder** [comment]
Oh sorry, I've not checked the source, just the shipped package.
No rush on this, I was just trying to be helpful.

On my use react-look@1.0.0-beta8 is working well with react@^15.0.1, just the peer-dependencie that I noticed.

Thank you for the fast response and keep up the good job.
