### ISSUE TITLE
StyleSheet.renderToString always empty on SSR

### ISSUE THREAD

**Issue by jordanh** [rofrischmann/react-look#267]
**Version**: 1.0.0 (beta5)
**Environment**: React
**Type**: General

-------------------
#### Description

Hiya! We've been [porting our project](https://github.com/ParabolInc/action/tree/inline-style-experiment) to `react-look` for the past week or so and so far have been absolutely in love with it.

Everything has been working swimmingly on the client side. SSR has been a bit more of a challenge. I suspect that it's our understanding of how things are wired together (i.e. an opportunity for documentation) vs. a bug.

We've got our server render wired similarly to [how its suggested in the docs](https://github.com/rofrischmann/react-look/blob/develop/packages/react-look/docs/GettingStarted.md#9-server-side-rendering):

```javascript
function renderApp(req, res, store, assets, renderProps) {
  const location = renderProps && renderProps.location && renderProps.location.pathname || '/';
  // Needed so some components can render based on location
  store.dispatch(push(location));
  lookConfig.userAgent = req.headers['user-agent'];
  lookConfig.styleElementId = '_look';
  const htmlString = renderToStaticMarkup(
    <LookRoot config={lookConfig}>
      <Html
        title='Action | Parabol Inc'
        lookStyleElementId='_look'
        lookCSSToken='<!-- appCSS -->'
        store={store}
        assets={assets}
        renderProps={renderProps}
      />
    </LookRoot>
  );
  const appCSS = StyleSheet.renderToString(lookConfig.prefixer);
  console.log(`appCSS: ${appCSS}`);
  res.write('<!DOCTYPE html>');
  res.write(htmlString.replace('<!-- appCSS -->', appCSS));
  res.end();
}
```

The `<Html/>` react component will expand to many more sub-components. Within these sub-components there are calls to `StyleSheet.create` which create component-level styles. However, we don't see `appCSS` return any CSS (it's always an empty string) _unless_ we call `StyleSheet.create` within the same file as the above `renderApp()` method.

A question:

How does `StyleSheet` maintain context across components so the SSR styles may be aggregated with `StyleSheet.renderToString(...)`?

I suspect this is what `<LookRoot/>` is for, but we must have something wired incorrectly...

Thank you!

**Comment by jordanh** [comment]
Some more information. Our application is divided into two parts which I will refer to as `server.js` and `app.js`.

`server.js` is an Express application that handles inbound http requests. `server.js` also imports `app.js`.

`app.js` exposes a single default function, the router, which matches `req.url` and returns a handler.

Both `server.js` and `app.js` require `react-look` We suspect that the `StyleContainer` singleton created by `react-look` is separate between `server.js` and `app.js`. We're testing that theory now...

**Comment by rofrischmann** [comment]
Hey @jordanh, thanks for your detailed issue report! I am pretty sure you're totally right with your theory and the singleton nature of StyleContainer is something that bothers me since implemented.
Server-side rendering issues should be fixed with https://github.com/rofrischmann/react-look/issues/275 but that still needs quite some time to be finished. 
If you find any other quick fix to this problem, feel free to tell me or send a PR as problems with SSR seem to be a real issue more ppl got.
This might also be interesting for @mattkrick and @wesleycoder, as it might also solve your problem.
> I also want to point out a plugin for SSR [react-look-server-rendering](https://github.com/dustin-H/react-look-server-rendering) by @dustin-H which even optimizes server-side rendered Look apps with routes.

**Comment by dustin-H** [comment]
Hi @jordanh,
This is a running app using react-look and SSR: [telaviv](https://github.com/dustin-H/telaviv)

I currently haven't finished a demo, but you can just clone it, run `npm install`, `npm run dev` and `npm start`. You can see something under `http://localhost:8000/lol/test`.

**Comment by jordanh** [comment]
Thank you @rofrischmann – we're huge fans of `react-look` already. Funny you bring up @mattkrick, we're already colluding. He opened a separate issue #276 vs. this 'General' question. I'll take the party over there and close this one 😄
