### ISSUE TITLE
Improve rendering mechanism

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/react-look#275]
Right now I am working on a complete new way to render styles written in JavaScript. It will be compatible with any javascript solution and is not bound to React yet shares a lot of ideas and principles with React's renderer itself. 
Building Look on top will not only remove a huge amount of complexity within Look itself, but will also improve the way styles are rendered, simplify Look's API and most likely even improve rendering performance at all.

Things to be considered/included:
- [ ] Performance loss on rerender caused by dynamic resolving? ( [#272](https://github.com/rofrischmann/react-look/issues/272) )

**Comment by nevir** [comment]
👍

**Comment by rofrischmann** [comment]
Turned out I was not able to create something that fits Looks complex core, created a new project (Fela) instead.
