### ISSUE TITLE
Support for delimiter case

### ISSUE THREAD

**Issue by AlastairTaft** [rofrischmann/react-look#283]
Could we get support for delimiter case? If I use the following code the css output in the document automatically has px appended `font-weight: 500px` which doesn't work.

```javascript
StyleSheet.addCSS( {
  'h2': {
    'font-weight': 500,
  }
})
```
The reason why I'd like delimiter case to work is so that I can use this in conjunction with the [cssx](https://github.com/krasimir/cssx) library and write css in my JavaScript files.

**Comment by rofrischmann** [comment]
Yeah should not be a problem actually. Just need to add delimiter-cased props to the unitless property list as well. I see if I can add that to the fix I am pushing today :)

**Comment by AlastairTaft** [comment]
Awesome thankyou 👍

**Comment by rofrischmann** [comment]
Turned I had to change some other dependencies first. We could get this one out now
