### ISSUE TITLE
Not able to install 

### ISSUE THREAD

**Issue by pixelpunch** [rofrischmann/react-look#287]
**Version**: 1.0.0 (beta5)
**Environment**: React 
**Type**: Bug 

-------------------
#### Description
Please try to add as much detail as possible. 

Not able to install. See Bug report. 
I am on Mac OSX - El Capitan. 
React - 0.15.0
Meteor - 1.3

#### Actual Behavior
```javascript
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "react-look" "--save"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react@15.0.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-dom@15.0.2 wants react@^15.0.2
npm ERR! peerinvalid Peer react-mounter@1.2.0 wants react@0.14.x || 15.x.x
npm ERR! peerinvalid Peer react-look@1.0.0 wants react@^0.14.3
```

#### Proposal
Any information on how this might be achieved.

**Code Example**:
```javascript
// your proposal here
```

**Comment by rofrischmann** [comment]
Oh well, seems like those errors are just peer dependency errors right? There should be no problem with this, just ignore it and start coding I guess. npm's peer dependency logic is a bit strange.

If there still is a problem which let's you not use Look, feel free to reopen this issue :)

**Comment by pixelpunch** [comment]
Thanks for the quick response. Yes, it is strange that it is throwing this error especially as your package doesn't depend explicitly on the earlier version. Will go ahead and code.
