### ISSUE TITLE
New install doesn't work 

### ISSUE THREAD

**Issue by pixelpunch** [rofrischmann/react-look#288]
**Version**: 1.0.0 (beta5)
**Environment**: React 
**Type**: Bug 
-------------------

#### Description

Doesn't work. Looks like it can't find the package - though it is showing up on node_modules - http://screencast.com/t/POEAG7qBql 
I had reported a  peer invalidity error earlier. 

#### Steps to reproduce
1. First step
2. Second step

#### Expected Behavior
```javascript
// your code here
```

#### Actual Behavior
```javascript
// your code here
```

#### Proposal
Any information on how this might be achieved.

**Code Example**:
```javascript
// your proposal here
```

**Comment by philpl** [comment]
This is a typo. You're trying to use `Stylesheet`, while it's actually called `StyleSheet`

**Comment by rofrischmann** [comment]
Lol. I really did not see this. I guess this can be closed then. Thanks @philpl
