### ISSUE TITLE
unique keys for child elements

### ISSUE THREAD

**Issue by travischoma** [rofrischmann/react-look#32]
I'm console warning in Chrome that reads:

Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of LookComponent. See https://fb.me/react-warning-keys for more information.

**Comment by rofrischmann** [comment]
I think this got nothing to do with look general as it is a React warning itself.
Check [this](https://facebook.github.io/react/docs/multiple-components.html#dynamic-children) for more information.

In look you **only** need a unique key if you want to apply a look with **user-action pseudo classes** to multiple components.
user-action pseudos are :hover, :active, :focus (deprecated: :valid, :invalid)
Look needs them to distinguish different components
