### ISSUE TITLE
Resolve Styles on props as well

### ISSUE THREAD

**Issue by rofrischmann** [rofrischmann/react-look#73]
We should also resolve styles that are declared on props e.g. 
```javascript
<Component myHeader={<div style={{color: 'red'}}>I should be red</div>}></Component>
```

**Comment by dehlen** [comment]
I tried to tackle this issue on my fork. Please have a look at it and if you wish I'll create a PR to merge the changes into the master repository.

Great lib btw.

Best Regards,
David
