### ISSUE TITLE
Pass Config as processArg to add new config options

### ISSUE THREAD

**Issue by dehlen** [rofrischmann/react-look#90]
It would be nice as a processor/mixin developer to be able to add additional config options (such as a custom matchMedia-method for server-side vendor prefixing).

Best Regards,
David

**Comment by rofrischmann** [comment]
Hmm yeah, this sounds quite convincing. Could be quite useful for any kind of processor/mixin that needs additional settings.

You may send a pull request if you considered adding that on your own.

Greets, Robin!

**Comment by dehlen** [comment]
Done, created PR ready to merge.

**Comment by rofrischmann** [comment]
Awesome! Thanks again
